name: ci

on:
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger

jobs:
  tests:
    name: Tests
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Go tests 
        run: go test ./...